version: '3.9'
services:
  backend:
    container_name: 'backend-compose'
    build:
      context: backend
      dockerfile: Dockerfile
    image: 'backend-compose'
    ports:
      - "4000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - backend-network

  frontend:
    container_name: 'frontend-compose'
    build:
      context: frontend
      dockerfile: Dockerfile
    image: 'frontend-compose'
    ports:
      - "8081:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - frontend-network

  postgres:
    container_name: 'postgres'
    image: postgres
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - pg-data:${POSTGRES_PGDATA}
    networks:
      - backend-network

volumes:
  pg-data:

networks:
  frontend-network:
  backend-network:
